interaction:
  actionCardDelayMs: 1000
  eventCardMinDelayMs: 10000
  eventCardMaxDelayMs: 20000
  eventCardMinDurationMs: 30000
  eventCardMaxDurationMs: 60000
  assets:
    markerSlotActive:
      url: slots/marker-slot-active_x-121_y-121.webp
    markerSlotInactive:
      url: slots/marker-slot-inactive_x-121_y-121.webp
  slotGroups:
    - id: technology
      type: action-card
      label:
        de: Technologie
        en: Technology
      slots:
        - markerSlot: { id: technology-ms-1, x: 134, y: 744, angle: 90 }
          cardSlot: { id: technology-cs-1, x: 497, y: 634, angle: 90 }
        - markerSlot: { id: technology-ms-2, x: 134, y: 1000, angle: 90 }
          cardSlot: { id: technology-cs-2, x: 497, y: 890, angle: 90 }
        - markerSlot: { id: technology-ms-3, x: 134, y: 1255, angle: 90 }
          cardSlot: { id: technology-cs-3, x: 497, y: 1145, angle: 90 }
      cards:
        - parameterTransformId: (T) Triple Diamantglas
          url: cards/technology/triple-diamond-glass.webp
        - parameterTransformId: (T) KI-Automatisierung
          url: cards/technology/ai-automation.webp
        - parameterTransformId: (T) Modular smartphone
          url: cards/technology/modular-smartphone.webp
        - parameterTransformId: (T) Planed Obsol
          url: cards/technology/planned-obsolescence.webp
        - parameterTransformId: (T) Software Upgrade
          url: cards/technology/software-upgrade.webp
    - id: policy
      type: action-card
      label:
        de: Regelung
        en: Policy
      slots:
        - markerSlot: { id: policy-ms-1, x: 1354, y: 2007, angle: 0 }
          cardSlot: { id: policy-cs-1, x: 1244, y: 1644, angle: 0 }
        - markerSlot: { id: policy-ms-2, x: 1610, y: 2007, angle: 0 }
          cardSlot: { id: policy-cs-2, x: 1500, y: 1644, angle: 0 }
        - markerSlot: { id: policy-ms-3, x: 1866, y: 2007, angle: 0 }
          cardSlot: { id: policy-cs-3, x: 1756, y: 1644, angle: 0 }
      cards:
        - parameterTransformId: (P) Schul-Repair-Café
          url: cards/policy/school-repair-cafe.webp
        - parameterTransformId: (P) Extreme Öko-Steuer
          url: cards/policy/extreme-eco-tax.webp
        - parameterTransformId: (P) Handy-Abo
          url: cards/policy/handy-abo.webp
        - parameterTransformId: (P) Recycle-Prämie
          url: cards/policy/recycle-bonus.webp
        - parameterTransformId: (P) Wartungsvertrag
          url: cards/policy/wartungsvertrag.webp
        - parameterTransformId: (P) Jugendschutz
          url: cards/policy/youth-protection.webp
        - parameterTransformId: (P) Ein-Telefon-Gesetz
          url: cards/policy/one-phone-law.webp
        - parameterTransformId: (P) BYOD
          url: cards/policy/byod.webp
        - parameterTransformId: (P) Handy Detox Day
          url: cards/policy/handy-detox-day.webp
    - id: event
      type: event-card
      label:
        de: Ereignisse
        en: Events
      markerSlot: { id: event-ms-1, x: 2157, y: 216, angle: 180 }
      cardSlots:
        - { id: event-cs-1, x: 2027, y: 324, angle: 180 }
        - { id: event-cs-2, x: 1771, y: 324, angle: 180 }
        - { id: event-cs-3, x: 1515, y: 324, angle: 180 }
      cards:
        - parameterTransformId: (E) Weltweite Chip-Krise
          url: cards/event/global-chip-crisis.webp
        - parameterTransformId: (E) Neues Ananas Phone
          url: cards/event/new-pineapple-phone.webp
        - parameterTransformId: (E) Sicherheitslücke
          url: cards/event/security-gap.webp
        - parameterTransformId: (E) Transport Streik
          url: cards/event/transportstreik.webp
        - parameterTransformId: (E) Deponie Streik
          url: cards/event/landfill-strike.webp
    - id: reduce
      type: basic
      label:
        de: Reduzieren
        en: Reduce
      slots:
        - { id: reduce-ms-1, x: 1521, y: 1205, angle: 0 }
        - { id: reduce-ms-2, x: 1762, y: 1267, angle: 0 }
        - { id: reduce-ms-2, x: 2012, y: 1301, angle: 0 }
      parameterTransformIds: [reduce, reduce, reduce]
    - id: reuse
      type: basic
      label:
        de: |
          Wieder-
          verwenden
        en: Reuse
      slots:
        - { id: reuse-ms-1, x: 3594, y: 892, angle: -90 }
        - { id: reuse-ms-2, x: 3603, y: 1144, angle: -90 }
        - { id: reuse-ms-3, x: 3613, y: 1399, angle: -90 }
      parameterTransformIds: [reuse, reuse, reuse]
    - id: repair
      type: basic
      label:
        de: Reparieren
        en: Repair
      slots:
        - { id: repair-ms-1, x: 1304, y: 889, angle: 180 }
        - { id: repair-ms-2, x: 1548, y: 816, angle: 180 }
        - { id: repair-ms-3, x: 1791, y: 744, angle: 180 }
      parameterTransformIds: [repair, repair, repair]
    - id: refurbish
      type: basic
      label:
        de: Erneuern
        en: Refurbish
      slots:
        - { id: refurbish-ms-1, x: 2607, y: 1924, angle: 0 }
        - { id: refurbish-ms-2, x: 2856, y: 1869, angle: 0 }
        - { id: refurbish-ms-3, x: 3101, y: 1814, angle: 0 }
      parameterTransformIds: [refurbish, refurbish, refurbish]
    - id: recycle
      type: basic
      label:
        de: |
          Wieder-
          verwerten
        en: Recycle
      slots:
        - { id: recycle-ms-1, x: 468, y: 472, angle: 180 }
        - { id: recycle-ms-2, x: 671, y: 315, angle: 180 }
        - { id: recycle-ms-3, x: 870, y: 161, angle: 180 }
      parameterTransformIds: [recycle, recycle, recycle]
